# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [backup]
  pull_request:
    branches: [backup]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: npm install
      - run: npm test
      - run: npm install hexo --save
      # - run: curl -L -O https://github.com/iissnan/hexo-theme-next/archive/v5.1.4.zip && unzip v5.1.4.zip -d themes/next

      # Runs a single command using the runners shell
      - name: deploy generated files
        # run: hexo g -d
        run: hexo g
    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
